"""Structural protocols (duck-typing seams) for gRPC settings and servers.

Settings fields are declared as read-only properties, not plain attributes:
protocol attributes are invariant under type checking, while read-only
properties are covariant — implementations may narrow field types (e.g. a
pydantic model typing ``compression_algorithm`` as a ``Literal``) and still
satisfy the protocol.
"""

from typing import TYPE_CHECKING, Any, NewType, Protocol

import grpc

if TYPE_CHECKING:
    from collections.abc import Coroutine

# Typed DI key for the fully-qualified gRPC service name (avoids ambiguous bare `str`).
GrpcServiceName = NewType("GrpcServiceName", str)


class GrpcSettingsProtocol(Protocol):
    """Protocol for gRPC channel-tuning settings."""

    @property
    def host(self) -> str: ...
    @property
    def port(self) -> int: ...
    @property
    def keepalive_time_ms(self) -> int: ...
    @property
    def keepalive_timeout_ms(self) -> int: ...
    @property
    def keepalive_permit_without_calls(self) -> bool: ...
    @property
    def http2_min_recv_ping_interval_without_data_ms(self) -> int: ...
    @property
    def http2_max_pings_without_data(self) -> int: ...
    @property
    def max_send_message_length(self) -> int: ...
    @property
    def max_receive_message_length(self) -> int: ...
    @property
    def max_metadata_size(self) -> int: ...
    @property
    def initial_stream_window_size(self) -> int: ...
    @property
    def initial_connection_window_size(self) -> int: ...
    @property
    def max_connection_idle_ms(self) -> int | None: ...
    @property
    def max_connection_age_ms(self) -> int | None: ...
    @property
    def max_connection_age_grace_ms(self) -> int | None: ...
    @property
    def compression_algorithm(self) -> str | None: ...
    @property
    def max_concurrent_rpcs(self) -> int | None: ...


class GrpcSslSettingsProtocol(Protocol):
    """Protocol for gRPC SSL/TLS settings."""

    @property
    def ssl_enabled(self) -> bool: ...
    @property
    def ssl_cert_file(self) -> str | None: ...
    @property
    def ssl_key_file(self) -> str | None: ...
    @property
    def ssl_ca_file(self) -> str | None: ...
    @property
    def ssl_client_auth(self) -> bool: ...
    @property
    def ssl_max_cert_size(self) -> int | None: ...


class GrpcServerSettingsProtocol(GrpcSettingsProtocol, GrpcSslSettingsProtocol, Protocol):
    """Protocol for the full gRPC server settings."""

    @property
    def grace_period(self) -> float: ...
    @property
    def enable_reflection(self) -> bool: ...
    @property
    def enable_channelz(self) -> bool: ...


class GrpcServerProtocol(Protocol):
    """Protocol for a synchronous gRPC server."""

    def add_insecure_port(self, address: str) -> int: ...
    def add_secure_port(self, address: str, credentials: grpc.ServerCredentials) -> int: ...
    def start(self) -> None: ...
    def stop(self, grace: float | None) -> None: ...


class GrpcAsyncServerProtocol(Protocol):
    """Protocol for an asynchronous gRPC server."""

    def add_insecure_port(self, address: str) -> int: ...
    def add_secure_port(self, address: str, credentials: grpc.ServerCredentials) -> int: ...
    def start(self) -> "Coroutine[Any, Any, None]": ...
    def stop(self, grace: float | None) -> "Coroutine[Any, Any, None]": ...
    def wait_for_termination(self, timeout: float | None = None) -> "Coroutine[None, None, bool]": ...


__all__ = [
    "GrpcAsyncServerProtocol",
    "GrpcServerProtocol",
    "GrpcServerSettingsProtocol",
    "GrpcServiceName",
    "GrpcSettingsProtocol",
    "GrpcSslSettingsProtocol",
]
